services: docker

language: ruby
rvm:
  - 2.3.3
cache: bundler

.disable_global: &disable_global
  rvm: false
  cache: false
  before_install: false
  install: false
  script: false

env:
  global:
    - BEARS_ZIP_URL=https://codeload.github.com/coala/coala-bears/zip
jobs:
  include:
    - stage: moban
      <<: *disable_global
      language: python
      python: 3.6
      cache: pip
      install: pip install moban
      script: .ci/check_moban.sh

before_install:
  # Speeds installation of html-proofer
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - .ci/build.sh
  - curl -fsSL -o coala-bears.zip $BEARS_ZIP_URL/master
  - pip install coala-bears.zip[alldeps] --pre -U
  - docker run -v=$(pwd):/app --workdir=/app coala/base coala --ci

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never

# Route your build to the container-based infrastructure for a faster build
sudo: false
